import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const COLORS = {
  primary: [0, 0, 0],
  green: [0, 0, 0],
  red: [0, 0, 0],
  blue: [0, 0, 0],
  orange: [0, 0, 0],
  gray: [80, 80, 80],
  darkText: [0, 0, 0],
  lightBorder: [180, 180, 180],
};

// Map unsupported Unicode currency symbols to ASCII-safe alternatives for jsPDF
const SYMBOL_MAP = { '৳': 'Tk ', '₹': 'Rs ', '¥': 'Y ', '€': 'EUR ', '£': 'GBP ' };

function safeSym(symbol) {
  return SYMBOL_MAP[symbol] || symbol;
}

function fmtCur(amt, symbol = 'Tk ') {
  const num = parseFloat(amt);
  if (isNaN(num)) return `${symbol}0.00`;
  return `${symbol}${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(d) {
  if (!d) return '';
  try {
    return new Date(d).toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' });
  } catch {
    return String(d);
  }
}

/**
 * Generate a PDF report and open it in a new tab.
 */
export function generateReportPdf({
  reportData,
  bank,
  currencySymbol,
  reportTypeLabel,
  showTransactions,
  showExpenses,
  actualHandCash,
  generatedBy,
}) {
  const sym = safeSym(currencySymbol || '৳');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  let y = 14;

  // ── Header ──
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.darkText);
  doc.setFont('helvetica', 'bold');
  doc.text(bank?.name || 'Bank Report', margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.gray);
  doc.text(
    `${reportTypeLabel}  |  ${fmtDate(reportData.dateFrom)} - ${fmtDate(reportData.dateTo)}`,
    margin,
    y
  );
  y += 5;
  doc.text(`Generated by: ${generatedBy || 'Unknown'}  |  ${new Date().toLocaleString()}`, margin, y);
  y += 3;

  // Divider
  doc.setDrawColor(...COLORS.lightBorder);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // ── Summary Cards (table-based to avoid overflow) ──
  const cards = [];

  if (showTransactions) {
    cards.push(
      { label: 'Total Deposits', value: fmtCur(reportData.totalDeposits || 0, sym), sub: `${reportData.depositCount || 0} txns`, color: COLORS.green },
      { label: 'Total Withdrawals', value: fmtCur(reportData.totalWithdrawals || 0, sym), sub: `${reportData.withdrawalCount || 0} txns`, color: COLORS.red },
      { label: 'Total Cash In', value: fmtCur(reportData.totalCashIn || 0, sym), sub: `${reportData.cashInCount || 0} txns`, color: COLORS.blue },
    );
  }
  if (showExpenses) {
    cards.push({ label: 'Total Expenses', value: fmtCur(reportData.totalExpenses || 0, sym), sub: `${reportData.expenseCount || 0} items`, color: COLORS.orange });
  }
  cards.push({ label: 'Hand Cash (System)', value: fmtCur(reportData.handCashBalance || 0, sym), sub: 'ERP Calculated', color: COLORS.primary });

  // Render cards as autoTable rows of 3 per row for proper wrapping
  const colsPerRow = 3;
  const cardAreaW = pageW - margin * 2;
  const gap = 4;
  const cardW = (cardAreaW - (colsPerRow - 1) * gap) / colsPerRow;
  const cardH = 22;

  for (let row = 0; row < Math.ceil(cards.length / colsPerRow); row++) {
    const rowCards = cards.slice(row * colsPerRow, (row + 1) * colsPerRow);

    rowCards.forEach((card, i) => {
      const x = margin + i * (cardW + gap);

      // Card border
      doc.setDrawColor(...COLORS.lightBorder);
      doc.setLineWidth(0.3);
      doc.roundedRect(x, y, cardW, cardH, 2, 2, 'S');

      // Label
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.gray);
      doc.setFont('helvetica', 'normal');
      doc.text(card.label, x + 3, y + 5.5);

      // Value — auto-shrink font to fit within card width
      let fontSize = 12;
      doc.setFont('helvetica', 'bold');
      while (fontSize > 6) {
        doc.setFontSize(fontSize);
        const tw = doc.getTextWidth(card.value);
        if (tw <= cardW - 6) break;
        fontSize -= 0.5;
      }
      doc.setTextColor(...card.color);
      doc.text(card.value, x + 3, y + 13);

      // Sub
      doc.setFontSize(6.5);
      doc.setTextColor(...COLORS.gray);
      doc.setFont('helvetica', 'normal');
      doc.text(card.sub, x + 3, y + 18.5);
    });

    y += cardH + 3;
  }
  y += 2;

  // ── Actual Hand Cash Verification ──
  doc.setDrawColor(...COLORS.green);
  doc.setLineWidth(0.4);
  doc.roundedRect(margin, y, pageW - margin * 2, 10, 2, 2, 'S');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.darkText);
  doc.setFont('helvetica', 'normal');
  doc.text(`Actual Hand Cash (Counted): ${fmtCur(actualHandCash, sym)}`, margin + 4, y + 6);
  doc.setTextColor(...COLORS.green);
  doc.setFont('helvetica', 'bold');
  doc.text('Verified [OK]', pageW - margin - 4, y + 6, { align: 'right' });
  y += 15;

  // ── Net Flow ──
  doc.setDrawColor(...COLORS.lightBorder);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, pageW - margin * 2, 14, 2, 2, 'S');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gray);
  doc.setFont('helvetica', 'normal');
  doc.text('Net Flow', pageW / 2, y + 4.5, { align: 'center' });
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.darkText);
  doc.setFont('helvetica', 'bold');
  doc.text(fmtCur(reportData.netFlow || 0, sym), pageW / 2, y + 11, { align: 'center' });
  y += 19;

  // ── Expenses by Category ──
  if (showExpenses && reportData.expensesByCategory && Object.keys(reportData.expensesByCategory).length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    doc.text('Expenses by Category', margin, y);
    y += 2;

    const catRows = Object.entries(reportData.expensesByCategory).map(([cat, amount]) => [
      cat,
      fmtCur(amount, sym),
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Category', 'Amount']],
      body: catRows,
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [230, 230, 230], textColor: [0, 0, 0], fontStyle: 'bold', fontSize: 7.5 },
      columnStyles: { 1: { halign: 'right' } },
      theme: 'plain',
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Transaction Details ──
  if (showTransactions && reportData.transactions?.length > 0) {
    if (y > 240) { doc.addPage(); y = 14; }

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    doc.text('Transaction Details', margin, y);
    y += 2;

    const txnRows = reportData.transactions.map((txn) => [
      fmtDate(txn.created_at),
      (txn.type || '').replace('_', ' ').replace(/^\w/, (c) => c.toUpperCase()),
      txn.customer_name || txn.customer_account || '-',
      txn.notes || '-',
      fmtCur(txn.amount, sym),
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Date', 'Type', 'Customer', 'Notes', 'Amount']],
      body: txnRows,
      styles: { fontSize: 7.5, cellPadding: 2, overflow: 'ellipsize' },
      headStyles: { fillColor: [230, 230, 230], textColor: [0, 0, 0], fontStyle: 'bold', fontSize: 7 },
      columnStyles: {
        0: { cellWidth: 26 },
        1: { cellWidth: 22 },
        4: { halign: 'right', cellWidth: 28 },
      },
      theme: 'plain',
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Expense Details ──
  if (showExpenses && reportData.expenses?.length > 0) {
    if (y > 240) { doc.addPage(); y = 14; }

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    doc.text('Expense Details', margin, y);
    y += 2;

    const expRows = reportData.expenses.map((exp) => [
      fmtDate(exp.created_at),
      exp.expense_categories?.name || '-',
      exp.description || '-',
      (exp.deduct_from || '').replace('_', ' ').replace(/^\w/, (c) => c.toUpperCase()),
      fmtCur(exp.amount, sym),
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Date', 'Category', 'Description', 'Deducted From', 'Amount']],
      body: expRows,
      styles: { fontSize: 7.5, cellPadding: 2, overflow: 'ellipsize' },
      headStyles: { fillColor: [230, 230, 230], textColor: [0, 0, 0], fontStyle: 'bold', fontSize: 7 },
      columnStyles: {
        0: { cellWidth: 26 },
        4: { halign: 'right', cellWidth: 28 },
      },
      theme: 'plain',
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Signature Section ──
  // Ensure enough space; if not, add a new page
  if (y > pageH - 50) {
    doc.addPage();
    y = 14;
  }

  y += 10;
  const sigLineW = 60;
  const sigLeftX = margin;
  const sigRightX = pageW - margin - sigLineW;

  doc.setDrawColor(...COLORS.darkText);
  doc.setLineWidth(0.3);

  // Left: Agent/CSO signature
  doc.line(sigLeftX, y, sigLeftX + sigLineW, y);
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.darkText);
  doc.setFont('helvetica', 'normal');
  doc.text('Signature of Agent / CSO', sigLeftX, y + 4);
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.gray);
  doc.text('Name: ____________________________', sigLeftX, y + 9);
  doc.text('Date: ____________________________', sigLeftX, y + 14);

  // Right: Authorized signature
  doc.setDrawColor(...COLORS.darkText);
  doc.line(sigRightX, y, sigRightX + sigLineW, y);
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.darkText);
  doc.setFont('helvetica', 'normal');
  doc.text('Authorized Signature', sigRightX, y + 4);
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.gray);
  doc.text('Name: ____________________________', sigRightX, y + 9);
  doc.text('Date: ____________________________', sigRightX, y + 14);

  // ── Footer on every page ──
  const pageCount = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    const footerY = pageH - 8;
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.gray);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by ${generatedBy || 'Unknown'}  |  ${bank?.name || 'AgentBank ERP'}  |  Page ${p} of ${pageCount}`,
      pageW / 2,
      footerY,
      { align: 'center' }
    );
  }

  // Open in new tab
  const pdfBlob = doc.output('blob');
  const url = URL.createObjectURL(pdfBlob);
  window.open(url, '_blank');
}
